"""Replay a HY-Motion WoodenMesh next to the Genesis MJCF collision proxy.

The high-resolution mesh is a visual-only Genesis entity.  Its vertices are
updated with ``RigidEntity.set_vverts``; the 22-joint MJCF remains the cheap
collision/kinematic layer.  This keeps the two responsibilities separate:
the mesh is used for appearance and the capsules/spheres are used for future
contact experiments.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import genesis as gs
import numpy as np
import torch

from generate_human_mjcf import HY_TO_GENESIS
from replay_human_mjcf import (
    SIM_DT,
    build_cubic_qpos_interpolator,
    interpolate_qpos,
    make_quaternion_sequence_continuous,
    prepare_points,
    qpos_for_frame,
)


WORKSPACE = Path(__file__).resolve().parents[1]
DEFAULT_MOTION = WORKSPACE / "genesis-human-experiment/motions/prepared/final_full_cooperation_seed2026.npz"
DEFAULT_MODEL = WORKSPACE / "genesis-human-experiment/assets/human_22ball.xml"
DEFAULT_MODEL_DIR = WORKSPACE / "HY-Motion-1.0/scripts/gradio/static/assets/dump_wooden"
DEFAULT_REPORT = WORKSPACE / "genesis-human-experiment/reports/hymotion_mesh_genesis_smoke.json"
DEFAULT_OBJ = WORKSPACE / "genesis-human-experiment/assets/generated/hymotion_mesh_initial.obj"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--motion", type=Path, default=DEFAULT_MOTION)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--mesh-obj", type=Path, default=DEFAULT_OBJ)
    parser.add_argument("--seconds", type=float, default=None)
    parser.add_argument("--viewer", action="store_true")
    parser.add_argument("--fixed-camera", action="store_true")
    parser.add_argument("--collision", action="store_true", help="Enable collision on the MJCF proxy.")
    parser.add_argument("--interpolation", choices=("cubic", "linear"), default="cubic")
    return parser.parse_args()


def load_wooden_vertices(motion_path: Path, model_dir: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    """Return Genesis-space vertices, faces, pelvis roots, and source FPS."""
    repo = model_dir.parents[4]
    if str(repo) not in sys.path:
        sys.path.insert(0, str(repo))
    from hymotion.pipeline.body_model import WoodenMesh

    with np.load(motion_path, allow_pickle=False) as data:
        poses = data["poses"].astype(np.float32)
        trans = data["trans"].astype(np.float32)
        fps = float(data["fps"][0]) if "fps" in data else 30.0

    mesh_model = WoodenMesh(model_path=str(model_dir))
    with torch.inference_mode():
        result = mesh_model(
            {
                "poses": torch.from_numpy(poses),
                "trans": torch.from_numpy(trans),
            }
        )
    vertices = result["vertices"].cpu().numpy().astype(np.float32) @ HY_TO_GENESIS.T
    # keypoints3d is root-relative; the exported trans is already included in
    # the stored keypoints used by the MJCF retargeter, so add it exactly once.
    mesh_roots = (result["keypoints3d"][:, 0].cpu().numpy().astype(np.float32) + trans) @ HY_TO_GENESIS.T
    faces = np.asarray(mesh_model.faces, dtype=np.int32)
    return vertices, faces, mesh_roots, fps


def write_obj(path: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Create the static initial mesh used to allocate Genesis visual buffers."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by replay_hymotion_mesh_genesis.py\n")
        for vertex in vertices:
            handle.write(f"v {vertex[0]:.8f} {vertex[1]:.8f} {vertex[2]:.8f}\n")
        for face in faces:
            handle.write(f"f {int(face[0]) + 1} {int(face[1]) + 1} {int(face[2]) + 1}\n")


def run(args: argparse.Namespace) -> dict[str, object]:
    motion_path = args.motion.resolve()
    model_path = args.model.resolve()
    model_dir = args.model_dir.resolve()
    report_path = args.report.resolve()
    if not motion_path.is_file():
        raise FileNotFoundError(motion_path)
    if not model_path.is_file():
        raise FileNotFoundError(model_path)
    if not (model_dir / "v_template.bin").is_file():
        raise FileNotFoundError(model_dir / "v_template.bin")

    vertices, faces, mesh_roots, fps = load_wooden_vertices(motion_path, model_dir)
    write_obj(args.mesh_obj.resolve(), vertices[0], faces)

    # The MJCF proxy uses the same prepared keypoints as the established
    # replay path.  The mesh root is aligned to the proxy pelvis each frame;
    # this removes only the small representation/root-origin difference and
    # does not alter the mesh's joint rotations or skinning.
    points, point_fps = prepare_points(motion_path)
    if abs(point_fps - fps) > 1e-4:
        raise ValueError(f"FPS mismatch between motion metadata ({point_fps}) and mesh input ({fps})")
    rest = points[0]
    from generate_human_mjcf import rotation_from_basis

    rest_basis = rotation_from_basis(rest)
    requested_duration = (len(points) - 1) / fps if args.seconds is None else min(args.seconds, (len(points) - 1) / fps)
    steps = int(np.ceil(requested_duration / SIM_DT))

    gs.init(backend=gs.cpu, precision="32")
    scene = gs.Scene(
        sim_options=gs.options.SimOptions(dt=SIM_DT, gravity=(0.0, 0.0, 0.0)),
        rigid_options=gs.options.RigidOptions(enable_collision=args.collision, box_box_detection=True),
        viewer_options=gs.options.ViewerOptions(
            res=(1280, 800),
            camera_pos=(3.2, -3.8, 1.9),
            camera_lookat=(0.0, 0.0, 0.9),
            camera_fov=45,
        ),
        show_viewer=args.viewer,
    )
    scene.add_entity(gs.morphs.Plane(), name="ground")
    human = scene.add_entity(
        gs.morphs.MJCF(file=str(model_path), requires_jac_and_IK=False),
        name="hymotion_human_22ball",
    )
    mesh = scene.add_entity(
        gs.morphs.Mesh(
            file=str(args.mesh_obj.resolve()),
            fixed=True,
            visualization=True,
            collision=False,
            enable_custom_vverts=True,
            decimate=False,
            convexify=False,
            file_meshes_are_zup=True,
        ),
        name="hymotion_woodenmesh_visual",
    )
    scene.build()
    if mesh.n_vverts != vertices.shape[1]:
        raise RuntimeError(f"Genesis vertex count changed: expected {vertices.shape[1]}, got {mesh.n_vverts}")
    mesh.set_vverts(vertices[0])
    roundtrip = mesh.get_vverts()
    if hasattr(roundtrip, "detach"):
        roundtrip = roundtrip.detach().cpu().numpy()
    roundtrip_error = float(np.max(np.abs(np.asarray(roundtrip) - vertices[0])))
    mesh_vertex_order_verified = roundtrip_error <= 1e-5
    if not mesh_vertex_order_verified:
        raise RuntimeError(f"Genesis visual vertex round-trip error is {roundtrip_error:.3e} m")
    if args.viewer and not args.fixed_camera:
        scene.viewer.follow_entity(
            human,
            fixed_axis=(None, None, None),
            smoothing=0.92,
            fix_orientation=False,
        )

    source_qposes = np.stack(
        [qpos_for_frame(frame_points, rest, rest_basis, human) for frame_points in points]
    ).astype(np.float32)
    source_qposes = make_quaternion_sequence_continuous(source_qposes)
    cubic_qpos_at = build_cubic_qpos_interpolator(source_qposes, fps) if args.interpolation == "cubic" else None
    free_start = human.get_joint(name="pelvis_free").q_start
    max_mesh_proxy_root_error = 0.0
    max_mesh_step = 0.0
    max_proxy_step = 0.0
    previous_mesh = None
    previous_proxy = None
    started = time.perf_counter()
    for step in range(steps + 1):
        time_seconds = min(step * SIM_DT, requested_duration)
        source_position = time_seconds * fps
        left = min(int(np.floor(source_position)), len(points) - 1)
        right = min(left + 1, len(points) - 1)
        alpha = source_position - left if right != left else 0.0
        if cubic_qpos_at is not None:
            qpos = cubic_qpos_at(time_seconds)
        else:
            qpos = interpolate_qpos(source_qposes[left], source_qposes[right], alpha)
        human.set_qpos(qpos, zero_velocity=True)
        scene.step() if args.viewer else scene.step(update_visualizer=False)
        # Mesh vertices are world-space positions in Genesis' custom buffer.
        proxy_root = qpos[free_start : free_start + 3]
        mesh_root = mesh_roots[left] if right == left else (1.0 - alpha) * mesh_roots[left] + alpha * mesh_roots[right]
        aligned = vertices[left] if right == left else (1.0 - alpha) * vertices[left] + alpha * vertices[right]
        aligned = aligned + (proxy_root - mesh_root)
        mesh.set_vverts(aligned)
        root_error = float(np.linalg.norm((mesh_root + (proxy_root - mesh_root)) - proxy_root))
        max_mesh_proxy_root_error = max(max_mesh_proxy_root_error, root_error)
        if previous_mesh is not None:
            max_mesh_step = max(max_mesh_step, float(np.max(np.linalg.norm(aligned - previous_mesh, axis=1))))
        if previous_proxy is not None:
            max_proxy_step = max(max_proxy_step, float(np.linalg.norm(proxy_root - previous_proxy)))
        previous_mesh = aligned.copy()
        previous_proxy = proxy_root.copy()

    report = {
        "status": "success",
        "motion": str(motion_path),
        "mjcf_model": str(model_path),
        "wooden_model_dir": str(model_dir),
        "mesh_obj": str(args.mesh_obj.resolve()),
        "genesis_version": getattr(gs, "__version__", "unknown"),
        "vertices": int(vertices.shape[1]),
        "faces": int(faces.shape[0]),
        "frames": int(len(vertices)),
        "source_fps": fps,
        "duration_seconds": requested_duration,
        "steps": steps,
        "interpolation": args.interpolation,
        "visual_entity": "Genesis Mesh, collision=False, enable_custom_vverts=True",
        "collision_entity": "22-joint MJCF capsule/sphere proxy",
        "collision_enabled": bool(args.collision),
        "mesh_vertex_order_verified": mesh_vertex_order_verified,
        "mesh_vertex_roundtrip_error_m": roundtrip_error,
        "max_mesh_proxy_root_error_m": max_mesh_proxy_root_error,
        "max_mesh_vertex_step_m": max_mesh_step,
        "max_proxy_root_step_m": max_proxy_step,
        "elapsed_wall_seconds": time.perf_counter() - started,
        "viewer": bool(args.viewer),
        "note": "The high-resolution mesh is visual-only; the MJCF proxy is the future collision/interaction layer.",
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return report


if __name__ == "__main__":
    run(parse_args())
